# Generated by Django 4.0.3 on 2022-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('GameLevel', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CharacterColor', models.CharField(max_length=500)),
                ('CharacterName', models.CharField(max_length=500)),
                ('CharacterGender', models.CharField(max_length=500)),
                ('UserResponses', models.CharField(max_length=500, null=True, blank=True)),
                ('Result', models.CharField(max_length=500, null=True, blank=True)),
                ('TimeSpentPlaying', models.IntegerField(default=0)),
                ('NotifyParents', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserfullName', models.CharField(max_length=500)),
                ('Game', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UserEmail', models.CharField(max_length=500)),
                ('UserPhonenumber', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
                ('Userpassword', models.CharField(max_length=500)),
            ],
        ),
    ]
